name: 中青-Python
on:  
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 【中青-Python】' 
        run: |
          cd Youth
          python3 youth.py 
        env:
            YOUTH_HEADER1: ${{ secrets.YOUTH_HEADER_1 }}  #必须
            YOUTH_READBODY1: ${{ secrets.YOUTH_ARTBODY_1 }}  #必须
            YOUTH_READTIMEBODY1: ${{ secrets.YOUTH_TIME_1 }}  #必须
            BARK: ${{ secrets.BARK }}     # bark服务
            SCKEY: ${{ secrets.SCKEY }}   # server酱服务
            TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
            TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
