name: 中青看点-自动阅读A

on:
  workflow_dispatch:

  schedule:
     - cron: '10 */6 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点一】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_1_50 }}
      - name: '运行 【中青看点二】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_51_100 }}
      - name: '运行 【中青看点三】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_101_150 }}
      - name: '运行 【中青看点四】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_151_200 }}
      - name: '运行 【中青看点五】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_201_250 }}
      - name: '运行 【中青看点六】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_251_300 }}
      - name: '运行 【中青看点七】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_301_350 }}
      - name: '运行 【中青看点八】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_351_400 }}
      - name: '运行 【中青看点九】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_401_450 }}
      - name: '运行 【中青看点十】'  
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_451_500 }}
