name: Curtin-中青看点-1

on:
  workflow_dispatch:

  schedule:
     - cron: '20 6-12 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点1】'
        if: env.YOUTH_READ      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
